services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db
  youtube:
    build: .
    volumes:
      - type: bind
        source: .env
        target: /app/.env
      - type: bind
        source: ./yt_list.csv
        target: /app/yt_list.csv
    depends_on:
      - mongodb

